---
- name: Include RedHat specific tasks
  include_tasks: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Include Debian specific tasks
  include_tasks: Debian.yml
  when: ansible_os_family == "Debian"

- name: Check systemd version
  shell: "set -o pipefail; systemctl --version | head -1 | cut -d' ' -f2"
  register: systemctl_version
  changed_when: no

- name: Check code-server
  block:
  - name: Check code-server binary exists
    stat:
      path: "{{ bin_dir }}/code-server"
    register: code_server_exists

  - name: Check code-server v1 version
    command: code-server --version
    register: code_server_version
    when: code_server_major == '1' and
          code_server_exists.stat.exists
    changed_when: no

  - name: Check code-server v2 version
    shell: "set -o pipefail; code-server --version | head -1 | cut -d' ' -f3"
    register: code_server_version
    when: code_server_major != '1' and
          code_server_exists.stat.exists
    changed_when: no

- name: Install code-server
  block:
  - name: Download code-server
    become: yes
    unarchive:
      remote_src: yes
      src: "{{ code_server_tar_url }}"
      dest: "{{ bin_dir }}"
      extra_opts:
        - --strip-components=1
        - --wildcards
        - "*/code-server"
    notify: Restart code-server
    when: not code_server_exists.stat.exists or
          code_server_version.stdout != code_server_ver

  - name: Copy code-server systemd unit file
    become: yes
    template:
      src: code-server.service
      dest: "{{ systemd_unit_files_dir }}"
    notify: Restart code-server

  - name: Copy code-server systemd override file
    become: yes
    template:
      src: code-server.service.d/restart.conf
      dest: "{{ systemd_unit_files_dir }}/code-server.service.d/"
    notify: Restart code-server

- name: Configure code-server
  block:
  - name: Create code-server data dir
    file:
      path: "{{ code_server_data_dir }}"
      state: directory
      group: "{{ code_server_user }}"
      owner: "{{ code_server_user }}"
      mode: "0700"

  - name: Copy code-server env file
    template:
      src: env
      dest: "{{ code_server_data_dir }}"
      group: "{{ code_server_user }}"
      owner: "{{ code_server_user }}"
      mode: 0600
    notify: Restart code-server
    when: code_server_password is defined

    - name: Copy TLS certificate
      become: yes
      copy:
        remote_src: "{{ tls_cert_remote }}"
        src: "{{ tls_cert }}"
        dest: "{{ code_server_data_dir }}/tls.cert"
        mode: 0440
        group: "{{ code_server_user }}"
      notify: Restart code-server
      when: tls_cert is defined

    - name: Copy TLS key
      become: yes
      copy:
        remote_src: "{{ tls_key_remote }}"
        src: "{{ tls_key }}"
        dest: "{{ code_server_data_dir }}/tls.key"
        mode: 0440
        group: "{{ code_server_user }}"
      notify: Restart code-server
      when: tls_key is defined

- name: Enable code-server service
  become: yes
  systemd:
    name: code-server
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Sanity Test
  include_tasks: tests.yml