---
- name: Test connectivity locally
  wait_for:
    port: "{{ code_server_port }}"
    timeout: 10
  ignore_errors: yes

- name: Test connectivity remotely
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ proxy_port | default('{{ code_server_port }}') }}"
    timeout: 10
  delegate_to: localhost
  ignore_errors: yes
